<?php
$this->headLink()->appendStylesheet(
    $this->basePath() . 'modules/rcm-pws-profile-info/style.css'
);
?>
<div class="pwsOwnerPersonalInfo">
<div class="personalInfo">
    <div class="pwsOwnerName" style="font-weight: bold;"><h1><?= $ownersInfo['ownersName'] ?></h1></div>
    <div class="pwsOwnerPhone" style="font-size:16px;"><h2><?= $ownersInfo['ownersPhone'] ?></h2></div>
    <div class="pwsOwnerEmail" style="font-size:16px;"><h2><?= $ownersInfo['ownersEmail'] ?></h2></div>
</div>
    <img  width="100px" height="100px" src="<?=$this->escapeHtml($imgUrl)?>">
</div>